name: Deploy to Amazon EKS

on:
  push:
    branches:
      - develop

env:
  ECR_REPOSITORY: kilt/prototype-services
  ECR_IMAGE_TAG: latest-develop
  SHA_IMAGE_TAG: ${{ github.sha }}
  KUBECONFIG: '${{ github.workspace }}/.kube/kubeconfig'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker build \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:$ECR_IMAGE_TAG \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:$SHA_IMAGE_TAG \
          .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$ECR_IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$SHA_IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$ECR_IMAGE_TAG"
        echo "::set-output name=image-sha::$ECR_REGISTRY/$ECR_REPOSITORY:$SHA_IMAGE_TAG"

  publish_to_docker:
    name: Publish develop image to docker
    needs: deploy
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Login to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: |
        echo $DOCKER_PASS | docker login --username=$DOCKER_USER --password-stdin
    - name: Tag and push dev image to Docker Hub
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        DOCKER_REPOSITORY: kiltprotocol/demo-services
        DOCKER_IMAGE_TAG: develop
      run: |
        docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$ECR_IMAGE_TAG
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$ECR_IMAGE_TAG $DOCKER_REPOSITORY:$DOCKER_IMAGE_TAG
        docker push $DOCKER_REPOSITORY:$DOCKER_IMAGE_TAG